server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: activity-service
          uri: lb://activity-service
          predicates:
            - Path=/api/activities/**

        - id: recommendation-service
          uri: lb://recommendation-service
          predicates:
            - Path=/api/recommendations/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/fitzy/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG